name: generate_document

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
  workflow_dispatch:

jobs:
  generate_document:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: any.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
